volumes:
  etc_wireguard:


services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    labels:
      traefik.enable: "true"
      traefik.http.routers.wgeasy-http.service: wgeasy
      traefik.http.routers.wgeasy-http.entrypoints: http
      traefik.http.routers.wgeasy-http.middlewares: https-redirect
      traefik.http.routers.wgeasy-http.rule: Host(`${DOMAIN}`)

      traefik.http.routers.wgeasy-https.service: wgeasy
      traefik.http.routers.wgeasy-https.entrypoints: https
      traefik.http.routers.wgeasy-https.rule: Host(`${DOMAIN}`)
      traefik.http.routers.wgeasy-https.tls: "true"
      traefik.http.routers.wgeasy-https.tls.certresolver: le
      traefik.http.services.wgeasy.loadbalancer.server.port: '51821'
      # traefik.udp.routers.wgeasy-udp.entrypoints: 'udp'
      # traefik.udp.routers.wgeasy-udp.service: wgeasy-udp
      # traefik.udp.services.wgeasy-udp.loadbalancer.server.port: '51820'
    networks:
      - fr_default
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      # - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${DOMAIN}

      # Optional:
      - PASSWORD=${ADMIN_PASSWORD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=10.8.0.0/16
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/16 -o eth0 -j MASQUERADE && iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT && iptables -A FORWARD -i wg0 -j ACCEPT && iptables -A FORWARD -o wg0 -j ACCEPT
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

      # image: weejewel/wg-easy
    volumes:
      - ./config:/etc/wireguard
      - /home/frappe/docker/development/backend_management/storage:/storage_drive
    ports:
      - "51820:51820/udp"
      # - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  fr_default:
    external: true
